import type { Registry } from "./schema";

const registryComponents: Registry = [
	{
		name: "auto-form-component",
		type: "registry:block",
		registryDependencies: [
			"button",
			"input",
			"label",
			"card",
			"separator",
			"checkbox",
			"textarea",
			"radio-group",
			"select",
			"switch",
			"popover",
			"calendar",
			"badge",
			"command",
			"drawer",
			"sidebar",
		],
		dependencies: ["zod-auto-form"],
		files: [
			"ui/auto-form/button.tsx",
			"ui/auto-form/input.tsx",
			"ui/auto-form/FieldWarper.tsx",
			"ui/auto-form/textarea.tsx",
			"ui/auto-form/checkbox_ui_1.tsx",
			"ui/auto-form/checkbox_ui_2.tsx",
			"ui/auto-form/radio-group.tsx",
			"ui/auto-form/select.tsx",
			"ui/auto-form/switch.tsx",
			"ui/auto-form/date-time-picker.tsx",
			"ui/auto-form/AutoFormGroupedFieldsWrapper.tsx",
			"ui/auto-form/AutoFormArrayWrapper.tsx",
			"ui/auto-form/AutoFormObjectWrapper.tsx",
			"ui/auto-form/form.tsx",
			"ui/auto-form/multi-select.tsx",
			"ui/auto-form/number-input.tsx",
			"ui/auto-form/base-multi-select.tsx",
			"ui/auto-form/base-time-picker.tsx",
			"ui/auto-form/index.tsx",
		],
	},
	{
		name: "auto-table-component",
		type: "registry:block",
		registryDependencies: ["avatar", "skeleton", "badge", "table"],
		dependencies: ["raw-auto-table-zod", "date-fns"],
		files: [
			"ui/auto-table/index.tsx",
			"ui/auto-table/table.tsx",
			"ui/auto-table/row-based-loading.tsx",
			"ui/auto-table/full-table-loading.tsx",
			"ui/auto-table/avatar.tsx",
			"ui/auto-table/text.tsx",
			"ui/auto-table/number.tsx",
			"ui/auto-table/enum.tsx",
			"ui/auto-table/date.tsx",
			"ui/auto-table/boolean.tsx",
			"ui/auto-table/multi-boolean.tsx",
			"ui/auto-table/multi-date.tsx",
			"ui/auto-table/multi-enum.tsx",
			"ui/auto-table/multi-number.tsx",
			"ui/auto-table/multi-string.tsx",
		],
	},
	{
		name: "auto-thing-component",
		type: "registry:block",
		registryDependencies: [
			"button",
			"card",
			"separator",
			"popover",
			"drawer",
			"sidebar",
			"badge",
			"tooltip",
			"dialog",
			"alert-dialog",
			"accordion",
			"input",
		],
		dependencies: ["auto-thing-zod"],
		files: [
			"ui/auto-thing/index.tsx",
			"ui/auto-thing/ActionButtonWrapper.tsx",
			"ui/auto-thing/CreateModal.tsx",
			"ui/auto-thing/DeleteButtonDetails.tsx",
			"ui/auto-thing/DeleteModal.tsx",
			"ui/auto-thing/EditButtonDetails.tsx",
			"ui/auto-thing/EditModal.tsx",
			"ui/auto-thing/SearchFilterWrapper.tsx",
			"ui/auto-thing/TableWrapperCard.tsx",
			"ui/auto-thing/ViewButtonDetails.tsx",
			"ui/auto-thing/ViewModal.tsx",
			"ui/auto-thing/types.tsx",
			"ui/auto-thing/DescriptionList.tsx",
			"ui/auto-thing/ResponsiveModal.tsx",
		],
	},
];

export { registryComponents };
